# Generated by Django 4.2.1 on 2023-08-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cocina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "image",
                    models.ImageField(upload_to="proyects", verbose_name="Imagen"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha actualizada"
                    ),
                ),
                (
                    "estufa",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sistema Operativo",
                    ),
                ),
                (
                    "tipo_gas_induccion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="tipo"
                    ),
                ),
                (
                    "altura",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="altura"
                    ),
                ),
                (
                    "ancho",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ancho"
                    ),
                ),
                (
                    "peso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="peso"
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="consumo"
                    ),
                ),
                (
                    "garantia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="garantia"
                    ),
                ),
            ],
            options={
                "verbose_name": "cocina",
                "verbose_name_plural": "cocina",
            },
        ),
        migrations.CreateModel(
            name="Lavadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "image",
                    models.ImageField(upload_to="proyects", verbose_name="Imagen"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha actualizada"
                    ),
                ),
                (
                    "capacidad",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="capacidad"
                    ),
                ),
                (
                    "altura",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="altura"
                    ),
                ),
                (
                    "ancho",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ancho"
                    ),
                ),
                (
                    "peso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="peso"
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="consumo"
                    ),
                ),
                (
                    "garantia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="garantia"
                    ),
                ),
            ],
            options={
                "verbose_name": "lavadora",
                "verbose_name_plural": "lavadora",
            },
        ),
        migrations.CreateModel(
            name="Licuadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "image",
                    models.ImageField(upload_to="proyects", verbose_name="Imagen"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha actualizada"
                    ),
                ),
                (
                    "velocidades",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="velocidades",
                    ),
                ),
                (
                    "altura",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="altura"
                    ),
                ),
                (
                    "vaso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="vaso"
                    ),
                ),
                (
                    "peso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="peso"
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="consumo"
                    ),
                ),
                (
                    "garantia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="garantia"
                    ),
                ),
            ],
            options={
                "verbose_name": "licuadora",
                "verbose_name_plural": "licuadora",
            },
        ),
        migrations.CreateModel(
            name="Microondas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "image",
                    models.ImageField(upload_to="proyects", verbose_name="Imagen"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha actualizada"
                    ),
                ),
                (
                    "capacidad",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="capacidad"
                    ),
                ),
                (
                    "altura",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="altura"
                    ),
                ),
                (
                    "ancho",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ancho"
                    ),
                ),
                (
                    "peso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="peso"
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="consumo"
                    ),
                ),
                (
                    "garantia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="garantia"
                    ),
                ),
            ],
            options={
                "verbose_name": "microondas",
                "verbose_name_plural": "microondas",
            },
        ),
        migrations.CreateModel(
            name="Refrigeradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "image",
                    models.ImageField(upload_to="proyects", verbose_name="Imagen"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha actualizada"
                    ),
                ),
                (
                    "capacidad",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="capacidad"
                    ),
                ),
                (
                    "altura",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="altura"
                    ),
                ),
                (
                    "ancho",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ancho"
                    ),
                ),
                (
                    "peso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="peso"
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="consumo"
                    ),
                ),
                (
                    "garantia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="garantia"
                    ),
                ),
            ],
            options={
                "verbose_name": "refrigeradora",
                "verbose_name_plural": "refrigeradoras",
            },
        ),
        migrations.CreateModel(
            name="Televisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                (
                    "image",
                    models.ImageField(upload_to="proyects", verbose_name="Imagen"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha actualizada"
                    ),
                ),
                (
                    "sistema",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sistema Operativo",
                    ),
                ),
                (
                    "altura",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="altura"
                    ),
                ),
                (
                    "ancho",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ancho"
                    ),
                ),
                (
                    "peso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="peso"
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="consumo"
                    ),
                ),
                (
                    "garantia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="garantia"
                    ),
                ),
            ],
            options={
                "verbose_name": "televisor",
                "verbose_name_plural": "televisor",
            },
        ),
    ]
