# Generated by Django 4.2.1 on 2023-08-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombres_completos",
                    models.CharField(max_length=100, verbose_name="nombres completos"),
                ),
                ("correo", models.EmailField(max_length=254, verbose_name="email")),
                ("producto", models.CharField(max_length=1000, verbose_name="email")),
                (
                    "comentario",
                    models.CharField(max_length=200, verbose_name="comentario"),
                ),
            ],
            options={
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
            },
        ),
    ]
