# Generated by Django 4.2.1 on 2023-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="correo",
            field=models.EmailField(max_length=254, verbose_name="correo"),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="nombres_completos",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="producto",
            field=models.CharField(max_length=1000, verbose_name="producto"),
        ),
    ]
