# Generated by Django 4.2.1 on 2023-08-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_contacto_correo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="nombres_completos",
            new_name="nombre",
        ),
    ]
