# Generated by Django 4.2.1 on 2023-08-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_name_contacto_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="comment",
            new_name="comentario",
        ),
        migrations.RenameField(
            model_name="contacto",
            old_name="email",
            new_name="correo",
        ),
        migrations.RenameField(
            model_name="contacto",
            old_name="related_product",
            new_name="producto",
        ),
    ]
