# Generated by Django 4.2.1 on 2023-08-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_comment_contacto_comentario_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cocina",
            options={"verbose_name": "cocinas", "verbose_name_plural": "cocinas"},
        ),
        migrations.AlterModelOptions(
            name="lavadora",
            options={"verbose_name": "lavadoras", "verbose_name_plural": "lavadoras"},
        ),
        migrations.AlterModelOptions(
            name="licuadora",
            options={"verbose_name": "licuadoras", "verbose_name_plural": "licuadoras"},
        ),
        migrations.AlterModelOptions(
            name="refrigeradora",
            options={
                "verbose_name": "refrigeradoras",
                "verbose_name_plural": "refrigeradoras",
            },
        ),
        migrations.AlterModelOptions(
            name="televisor",
            options={"verbose_name": "televisors", "verbose_name_plural": "televisors"},
        ),
        migrations.AlterField(
            model_name="cocina",
            name="estufa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numero de Estufas"
            ),
        ),
        migrations.AlterField(
            model_name="cocina",
            name="tipo_gas_induccion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo de Cocina"
            ),
        ),
    ]
