# Generated by Django 4.2.1 on 2023-08-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_cocina_options_alter_lavadora_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Microondas",
            new_name="Microonda",
        ),
    ]
